### PR TITLE
Feature/#2/repo setup

### PR DESCRIPTION
**Pull request by Exiledz5155**
## About this PR
#2 

## How to review
Pull down this branch and read **the entire** readme.md file for setup instructions and vscode extensions.

Ensure setup instructions work and venv is ignored properly by git (git status should not track it at all)
Ensure web-app runs

### CODE REVIEW

**Review by CalvinDudd — APPROVED** [review]
Assuming this is the best Next.js repo setup, I'll just go ahead and approve.

**Comment by Exiledz5155** [comment]
> Assuming this is the best Next.js repo setup, I'll just go ahead and approve.

Yep, this is just latest nextjs in additional to all the Python stuff we'll need for ML. All in one repo under one git tracking

**Review by marcus-gustafson — APPROVED** [review]
LGTM
Probably dont need vercel auto deploy on rn tho

**Comment by Exiledz5155** [comment]
> LGTM Probably dont need vercel auto deploy on rn tho

Yea I agree, I'm just making sure it works atm

**Pull request merged**
